name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: sa-east-1           # Define a região como sa-east-1
        mask-password: true         # Mascarar a senha do Docker
        registry-type: private
        skip-logout: false

    - name: Build and Push Redis Image
      run: |
        docker build -t redis:latest -f Dockerfile.redis .
        docker tag redis:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/redis:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/redis:latest

    - name: Build and Push RabbitMQ Image
      run: |
        docker build -t rabbitmq:latest -f Dockerfile.rabbitmq .
        docker tag rabbitmq:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/rabbitmq:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/rabbitmq:latest

    - name: Build and Push MongoDB Image
      run: |
        docker build -t mongo:latest -f Dockerfile.mongodb .
        docker tag mongo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/mongo:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/mongo:latest

  deploy:
    name: Deploy to ECS with Terraform
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: sa-east-1        # Define a região no ambiente do Terraform
